version: '3'

services:
 database:
    image: bitnami/postgresql
    ports: 
      - '5432:5432'
    container_name: Finance
    restart: always
    volumes: 
      - Finance-disk:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Finance
volumes: 
  Finance-disk: